#!/bin/sh
set -e

case "$1" in
configure)
    ldconfig
    if ! getent passwd scribe >/dev/null; then
      adduser --disabled-password  --quiet --system \
        --home /var/run/scribe --no-create-home \
        --gecos "Scribe daemon" --group scribe
    fi
        ;;
esac

# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules  scribe.public
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/scribe" ]; then
	update-rc.d scribe defaults >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d scribe start || exit $?
	else
		/etc/init.d/scribe start || exit $?
	fi
fi
# End automatically added section

