#!/bin/sh
set -e

case "$1" in
purge)
#        update-rc.d scribe remove
        ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d scribe remove >/dev/null || exit $?
fi
# End automatically added section

